name: firebase_kit
description: Firebase integration kit for Flutter applications. Provides streamlined Firebase services including Analytics, Authentication, Crashlytics, Cloud Firestore, and Cloud Messaging.
version: 1.0.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/firebase-kit
issue_tracker: https://github.com/nylo-core/firebase-kit/issues
documentation: https://github.com/nylo-core/
funding:
  - https://github.com/sponsors/agordn52
topics:
  - firebase
  - firebase-kit

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  service_runner: ^1.0.0
  # Firebase packages
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  firebase_core_platform_interface: ^6.0.2

flutter:
  uses-material-design: true

screenshots:
  - description: The FirebaseKit package logo.
    path: screenshots/logo.png